# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quangvhg/Dropbox/workspace/cryptonite_hash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quangvhg/Dropbox/workspace/cryptonite_hash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quangvhg/Dropbox/workspace/cryptonite_hash/CMakeFiles /home/quangvhg/Dropbox/workspace/cryptonite_hash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quangvhg/Dropbox/workspace/cryptonite_hash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cryptonite_hash

# Build rule for target.
cryptonite_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonite_hash
.PHONY : cryptonite_hash

# fast build rule for target.
cryptonite_hash/fast:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/build
.PHONY : cryptonite_hash/fast

asm/aesb-x64.o: asm/aesb-x64.S.o

.PHONY : asm/aesb-x64.o

# target to build an object file
asm/aesb-x64.S.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/asm/aesb-x64.S.o
.PHONY : asm/aesb-x64.S.o

crypto/aesb.o: crypto/aesb.c.o

.PHONY : crypto/aesb.o

# target to build an object file
crypto/aesb.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/aesb.c.o
.PHONY : crypto/aesb.c.o

crypto/aesb.i: crypto/aesb.c.i

.PHONY : crypto/aesb.i

# target to preprocess a source file
crypto/aesb.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/aesb.c.i
.PHONY : crypto/aesb.c.i

crypto/aesb.s: crypto/aesb.c.s

.PHONY : crypto/aesb.s

# target to generate assembly for a file
crypto/aesb.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/aesb.c.s
.PHONY : crypto/aesb.c.s

crypto/c_blake256.o: crypto/c_blake256.c.o

.PHONY : crypto/c_blake256.o

# target to build an object file
crypto/c_blake256.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_blake256.c.o
.PHONY : crypto/c_blake256.c.o

crypto/c_blake256.i: crypto/c_blake256.c.i

.PHONY : crypto/c_blake256.i

# target to preprocess a source file
crypto/c_blake256.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_blake256.c.i
.PHONY : crypto/c_blake256.c.i

crypto/c_blake256.s: crypto/c_blake256.c.s

.PHONY : crypto/c_blake256.s

# target to generate assembly for a file
crypto/c_blake256.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_blake256.c.s
.PHONY : crypto/c_blake256.c.s

crypto/c_groestl.o: crypto/c_groestl.c.o

.PHONY : crypto/c_groestl.o

# target to build an object file
crypto/c_groestl.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_groestl.c.o
.PHONY : crypto/c_groestl.c.o

crypto/c_groestl.i: crypto/c_groestl.c.i

.PHONY : crypto/c_groestl.i

# target to preprocess a source file
crypto/c_groestl.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_groestl.c.i
.PHONY : crypto/c_groestl.c.i

crypto/c_groestl.s: crypto/c_groestl.c.s

.PHONY : crypto/c_groestl.s

# target to generate assembly for a file
crypto/c_groestl.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_groestl.c.s
.PHONY : crypto/c_groestl.c.s

crypto/c_jh.o: crypto/c_jh.c.o

.PHONY : crypto/c_jh.o

# target to build an object file
crypto/c_jh.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_jh.c.o
.PHONY : crypto/c_jh.c.o

crypto/c_jh.i: crypto/c_jh.c.i

.PHONY : crypto/c_jh.i

# target to preprocess a source file
crypto/c_jh.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_jh.c.i
.PHONY : crypto/c_jh.c.i

crypto/c_jh.s: crypto/c_jh.c.s

.PHONY : crypto/c_jh.s

# target to generate assembly for a file
crypto/c_jh.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_jh.c.s
.PHONY : crypto/c_jh.c.s

crypto/c_keccak.o: crypto/c_keccak.c.o

.PHONY : crypto/c_keccak.o

# target to build an object file
crypto/c_keccak.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_keccak.c.o
.PHONY : crypto/c_keccak.c.o

crypto/c_keccak.i: crypto/c_keccak.c.i

.PHONY : crypto/c_keccak.i

# target to preprocess a source file
crypto/c_keccak.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_keccak.c.i
.PHONY : crypto/c_keccak.c.i

crypto/c_keccak.s: crypto/c_keccak.c.s

.PHONY : crypto/c_keccak.s

# target to generate assembly for a file
crypto/c_keccak.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_keccak.c.s
.PHONY : crypto/c_keccak.c.s

crypto/c_skein.o: crypto/c_skein.c.o

.PHONY : crypto/c_skein.o

# target to build an object file
crypto/c_skein.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_skein.c.o
.PHONY : crypto/c_skein.c.o

crypto/c_skein.i: crypto/c_skein.c.i

.PHONY : crypto/c_skein.i

# target to preprocess a source file
crypto/c_skein.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_skein.c.i
.PHONY : crypto/c_skein.c.i

crypto/c_skein.s: crypto/c_skein.c.s

.PHONY : crypto/c_skein.s

# target to generate assembly for a file
crypto/c_skein.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/c_skein.c.s
.PHONY : crypto/c_skein.c.s

crypto/hash.o: crypto/hash.c.o

.PHONY : crypto/hash.o

# target to build an object file
crypto/hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/hash.c.o
.PHONY : crypto/hash.c.o

crypto/hash.i: crypto/hash.c.i

.PHONY : crypto/hash.i

# target to preprocess a source file
crypto/hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/hash.c.i
.PHONY : crypto/hash.c.i

crypto/hash.s: crypto/hash.c.s

.PHONY : crypto/hash.s

# target to generate assembly for a file
crypto/hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/hash.c.s
.PHONY : crypto/hash.c.s

crypto/oaes_lib.o: crypto/oaes_lib.c.o

.PHONY : crypto/oaes_lib.o

# target to build an object file
crypto/oaes_lib.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/oaes_lib.c.o
.PHONY : crypto/oaes_lib.c.o

crypto/oaes_lib.i: crypto/oaes_lib.c.i

.PHONY : crypto/oaes_lib.i

# target to preprocess a source file
crypto/oaes_lib.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/oaes_lib.c.i
.PHONY : crypto/oaes_lib.c.i

crypto/oaes_lib.s: crypto/oaes_lib.c.s

.PHONY : crypto/oaes_lib.s

# target to generate assembly for a file
crypto/oaes_lib.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/crypto/oaes_lib.c.s
.PHONY : crypto/oaes_lib.c.s

cryptolite_hash.o: cryptolite_hash.c.o

.PHONY : cryptolite_hash.o

# target to build an object file
cryptolite_hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptolite_hash.c.o
.PHONY : cryptolite_hash.c.o

cryptolite_hash.i: cryptolite_hash.c.i

.PHONY : cryptolite_hash.i

# target to preprocess a source file
cryptolite_hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptolite_hash.c.i
.PHONY : cryptolite_hash.c.i

cryptolite_hash.s: cryptolite_hash.c.s

.PHONY : cryptolite_hash.s

# target to generate assembly for a file
cryptolite_hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptolite_hash.c.s
.PHONY : cryptolite_hash.c.s

cryptonite_hash.o: cryptonite_hash.c.o

.PHONY : cryptonite_hash.o

# target to build an object file
cryptonite_hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonite_hash.c.o
.PHONY : cryptonite_hash.c.o

cryptonite_hash.i: cryptonite_hash.c.i

.PHONY : cryptonite_hash.i

# target to preprocess a source file
cryptonite_hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonite_hash.c.i
.PHONY : cryptonite_hash.c.i

cryptonite_hash.s: cryptonite_hash.c.s

.PHONY : cryptonite_hash.s

# target to generate assembly for a file
cryptonite_hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonite_hash.c.s
.PHONY : cryptonite_hash.c.s

cryptonitehashmodule.o: cryptonitehashmodule.c.o

.PHONY : cryptonitehashmodule.o

# target to build an object file
cryptonitehashmodule.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonitehashmodule.c.o
.PHONY : cryptonitehashmodule.c.o

cryptonitehashmodule.i: cryptonitehashmodule.c.i

.PHONY : cryptonitehashmodule.i

# target to preprocess a source file
cryptonitehashmodule.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonitehashmodule.c.i
.PHONY : cryptonitehashmodule.c.i

cryptonitehashmodule.s: cryptonitehashmodule.c.s

.PHONY : cryptonitehashmodule.s

# target to generate assembly for a file
cryptonitehashmodule.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/cryptonitehashmodule.c.s
.PHONY : cryptonitehashmodule.c.s

sysinfos.o: sysinfos.c.o

.PHONY : sysinfos.o

# target to build an object file
sysinfos.c.o:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/sysinfos.c.o
.PHONY : sysinfos.c.o

sysinfos.i: sysinfos.c.i

.PHONY : sysinfos.i

# target to preprocess a source file
sysinfos.c.i:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/sysinfos.c.i
.PHONY : sysinfos.c.i

sysinfos.s: sysinfos.c.s

.PHONY : sysinfos.s

# target to generate assembly for a file
sysinfos.c.s:
	$(MAKE) -f CMakeFiles/cryptonite_hash.dir/build.make CMakeFiles/cryptonite_hash.dir/sysinfos.c.s
.PHONY : sysinfos.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cryptonite_hash"
	@echo "... asm/aesb-x64.o"
	@echo "... crypto/aesb.o"
	@echo "... crypto/aesb.i"
	@echo "... crypto/aesb.s"
	@echo "... crypto/c_blake256.o"
	@echo "... crypto/c_blake256.i"
	@echo "... crypto/c_blake256.s"
	@echo "... crypto/c_groestl.o"
	@echo "... crypto/c_groestl.i"
	@echo "... crypto/c_groestl.s"
	@echo "... crypto/c_jh.o"
	@echo "... crypto/c_jh.i"
	@echo "... crypto/c_jh.s"
	@echo "... crypto/c_keccak.o"
	@echo "... crypto/c_keccak.i"
	@echo "... crypto/c_keccak.s"
	@echo "... crypto/c_skein.o"
	@echo "... crypto/c_skein.i"
	@echo "... crypto/c_skein.s"
	@echo "... crypto/hash.o"
	@echo "... crypto/hash.i"
	@echo "... crypto/hash.s"
	@echo "... crypto/oaes_lib.o"
	@echo "... crypto/oaes_lib.i"
	@echo "... crypto/oaes_lib.s"
	@echo "... cryptolite_hash.o"
	@echo "... cryptolite_hash.i"
	@echo "... cryptolite_hash.s"
	@echo "... cryptonite_hash.o"
	@echo "... cryptonite_hash.i"
	@echo "... cryptonite_hash.s"
	@echo "... cryptonitehashmodule.o"
	@echo "... cryptonitehashmodule.i"
	@echo "... cryptonitehashmodule.s"
	@echo "... sysinfos.o"
	@echo "... sysinfos.i"
	@echo "... sysinfos.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

